In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data=pd.read_excel('therisingcostoflivinganditsimpactonindividualsingreatbritain22042022124930.xlsx',sheet_name='Table_1b')
print(data)

                             Table 1b: Cost of living         Unnamed: 1  \
0                  Great Britain, 16 to 27 March 2022                NaN
1   Source: Opinions and Lifestyle Survey (COVID-1...                NaN
2                       Date published: 25 April 2022                NaN
3   Some cells refer to notes which can be found i...                NaN
4   Freeze panes are turned on. To turn off freeze...                NaN
5                         Return to table of contents                NaN
6                                                 NaN  All persons total
7                                                 NaN                  %
8                                                 NaN                NaN
9   Over the last month, has your cost of living c...                NaN
10                    My cost of living has increased                 87
11              My cost of living has stayed the same                 13
12                    My cost of living has decreased                  1
13                                                NaN                NaN
14                                     Weighted count           52117165
15                                        Sample size               3090
16                                                NaN                NaN
17  Among those who said "My cost of living has in...                NaN
18  Over the last month, for what reasons has your...                NaN
19                 My income or earnings have reduced                  8
20              I have lost my job or stopped working                  1
21                     My hours of work have reduced                   3
22         My gas or electricity bills have increased                 83
23           My rent or mortgage costs have increased                 17
24            The price of my food shop has increased                 88
25                 The price of my fuel has increased                 77
26     The price of my public transport has increased                 15
27                                              Other                  4
28                                                NaN                NaN
29                                     Weighted count           45195052
30                                        Sample size               2730
31                                                NaN                NaN
32  Among those who said "My cost of living has in...                NaN
33  Which of the following are you doing because y...                NaN
34                          I am shopping around more                 37
35  I am spending less on food shopping and essent...                 33
36               I am spending less on non-essentials                 54
37                    I have started using foodbanks                   1
38                          I am using foodbanks more                 <1
39  I am cutting back on non-essential journeys in...                 39
40  I am using less fuel such as gas or electricit...                 45
41                              I am using my savings                 23
42        I am borrowing money from friends or family                  7
43  I am using credit more than usual, for example...                 11
44                 I am working more hours than usual                  5
45                                              Other                  1
46                                      None of these                 12
47                                                NaN                NaN
48                                     Weighted count           45165547
49                                        Sample size               2730
50                                                NaN                NaN

   Unnamed: 2 Unnamed: 3  Unnamed: 4              Unnamed: 5 Unnamed: 6  \
0         NaN        NaN         NaN                     NaN        NaN
1         NaN        NaN         NaN                     NaN        NaN
2         NaN        NaN         NaN                     NaN        NaN
3         NaN        NaN         NaN                     NaN        NaN
4         NaN        NaN         NaN                     NaN        NaN
5         NaN        NaN         NaN                     NaN        NaN
6         NaN        NaN         NaN  Most deprived [note 3]        NaN
7         LCL        UCL         NaN                       %        LCL
8         NaN        NaN         NaN                     NaN        NaN
9         NaN        NaN         NaN                     NaN        NaN
10         85         88         NaN                      82         76
11         11         14         NaN                      18         11
12          0          1         NaN                      ..         ..
13        NaN        NaN         NaN                     NaN        NaN
14        NaN        NaN         NaN                 5589075        NaN
15        NaN        NaN         NaN                     270        NaN
16        NaN        NaN         NaN                     NaN        NaN
17        NaN        NaN         NaN                     NaN        NaN
18        NaN        NaN         NaN                     NaN        NaN
19          7         10         NaN                      12          6
20          1          1         NaN                      ..         ..
21          2          4         NaN                       5          1
22         81         85         NaN                      77         70
23         15         19         NaN                      25         17
24         86         90         NaN                      87         81
25         75         79         NaN                      69         61
26         13         17         NaN                      11          6
27          3          5         NaN                       4          1
28        NaN        NaN         NaN                     NaN        NaN
29        NaN        NaN         NaN                 4592739        NaN
30        NaN        NaN         NaN                     220        NaN
31        NaN        NaN         NaN                     NaN        NaN
32        NaN        NaN         NaN                     NaN        NaN
33        NaN        NaN         NaN                     NaN        NaN
34         34         39         NaN                      39         31
35         31         36         NaN                      38         30
36         52         57         NaN                      64         56
37          0          1         NaN                       3          0
38          0         <1         NaN                      ..         ..
39         36         41         NaN                      39         31
40         43         48         NaN                      49         41
41         21         25         NaN                      21         14
42          6          9         NaN                      13          7
43         10         13         NaN                      15          9
44          4          7         NaN                       5          2
45          1          2         NaN                      ..         ..
46         11         14         NaN                       7          2
47        NaN        NaN         NaN                     NaN        NaN
48        NaN        NaN         NaN                 4560449        NaN
49        NaN        NaN         NaN                     220        NaN
50        NaN        NaN         NaN                     NaN        NaN

   Unnamed: 7  Unnamed: 8             Unnamed: 9  ... Unnamed: 34 Unnamed: 35  \
0         NaN         NaN                    NaN  ...         NaN         NaN
1         NaN         NaN                    NaN  ...         NaN         NaN
2         NaN         NaN                    NaN  ...         NaN         NaN
3         NaN         NaN                    NaN  ...         NaN         NaN
4         NaN         NaN                    NaN  ...         NaN         NaN
5         NaN         NaN                    NaN  ...         NaN         NaN
6         NaN         NaN  2nd quintile [note 3]  ...         NaN         NaN
7         UCL         NaN                      %  ...         LCL         UCL
8         NaN         NaN                    NaN  ...         NaN         NaN
9         NaN         NaN                    NaN  ...         NaN         NaN
10         89         NaN                     88  ...          86          93
11         24         NaN                     11  ...           6          13
12         ..         NaN                      1  ...           0           2
13        NaN         NaN                    NaN  ...         NaN         NaN
14        NaN         NaN                7854097  ...         NaN         NaN
15        NaN         NaN                    430  ...         NaN         NaN
16        NaN         NaN                    NaN  ...         NaN         NaN
17        NaN         NaN                    NaN  ...         NaN         NaN
18        NaN         NaN                    NaN  ...         NaN         NaN
19         18         NaN                      8  ...           4          10
20         ..         NaN                      2  ...          ..          ..
21          9         NaN                      6  ...           1           2
22         85         NaN                     87  ...          80          89
23         32         NaN                     20  ...          16          26
24         93         NaN                     86  ...          87          94
25         77         NaN                     72  ...          76          86
26         16         NaN                     18  ...          11          21
27          8         NaN                      3  ...           2           7
28        NaN         NaN                    NaN  ...         NaN         NaN
29        NaN         NaN                6916372  ...         NaN         NaN
30        NaN         NaN                    380  ...         NaN         NaN
31        NaN         NaN                    NaN  ...         NaN         NaN
32        NaN         NaN                    NaN  ...         NaN         NaN
33        NaN         NaN                    NaN  ...         NaN         NaN
34         48         NaN                     38  ...          29          40
35         46         NaN                     39  ...          30          41
36         72         NaN                     54  ...          51          62
37          5         NaN                      1  ...           0           1
38         ..         NaN                      1  ...          ..          ..
39         47         NaN                     35  ...          35          46
40         58         NaN                     42  ...          45          56
41         28         NaN                     20  ...          17          26
42         19         NaN                      9  ...           3          11
43         21         NaN                     14  ...          13          22
44          8         NaN                      6  ...           5          13
45         ..         NaN                      2  ...           0           2
46         11         NaN                     10  ...           7          14
47        NaN         NaN                    NaN  ...         NaN         NaN
48        NaN         NaN                6916372  ...         NaN         NaN
49        NaN         NaN                    380  ...         NaN         NaN
50        NaN         NaN                    NaN  ...         NaN         NaN

    Unnamed: 36                     Unnamed: 37 Unnamed: 38 Unnamed: 39  \
0           NaN                             NaN         NaN         NaN
1           NaN                             NaN         NaN         NaN
2           NaN                             NaN         NaN         NaN
3           NaN                             NaN         NaN         NaN
4           NaN                             NaN         NaN         NaN
5           NaN                             NaN         NaN         NaN
6           NaN  £30,000 up to £40,000 [note 4]         NaN         NaN
7           NaN                               %         LCL         UCL
8           NaN                             NaN         NaN         NaN
9           NaN                             NaN         NaN         NaN
10          NaN                              92          88          96
11          NaN                               7           3          11
12          NaN                               1           0           1
13          NaN                             NaN         NaN         NaN
14          NaN                         5534330         NaN         NaN
15          NaN                             320         NaN         NaN
16          NaN                             NaN         NaN         NaN
17          NaN                             NaN         NaN         NaN
18          NaN                             NaN         NaN         NaN
19          NaN                               5           2           9
20          NaN                              ..          ..          ..
21          NaN                               3           0           5
22          NaN                              91          87          95
23          NaN                              27          19          34
24          NaN                              89          84          94
25          NaN                              84          77          91
26          NaN                              17          10          24
27          NaN                               2           1           4
28          NaN                             NaN         NaN         NaN
29          NaN                         5105776         NaN         NaN
30          NaN                             300         NaN         NaN
31          NaN                             NaN         NaN         NaN
32          NaN                             NaN         NaN         NaN
33          NaN                             NaN         NaN         NaN
34          NaN                              41          33          49
35          NaN                              34          26          42
36          NaN                              60          52          68
37          NaN                              ..          ..          ..
38          NaN                              ..          ..          ..
39          NaN                              38          31          46
40          NaN                              47          39          55
41          NaN                              30          22          38
42          NaN                               8           4          13
43          NaN                              15          10          21
44          NaN                               6           3           9
45          NaN                              ..          ..          ..
46          NaN                              11           6          15
47          NaN                             NaN         NaN         NaN
48          NaN                         5105776         NaN         NaN
49          NaN                             300         NaN         NaN
50          NaN                             NaN         NaN         NaN

    Unnamed: 40               Unnamed: 41 Unnamed: 42 Unnamed: 43
0           NaN                       NaN         NaN         NaN
1           NaN                       NaN         NaN         NaN
2           NaN                       NaN         NaN         NaN
3           NaN                       NaN         NaN         NaN
4           NaN                       NaN         NaN         NaN
5           NaN                       NaN         NaN         NaN
6           NaN  £40,000 or more [note 4]         NaN         NaN
7           NaN                         %         LCL         UCL
8           NaN                       NaN         NaN         NaN
9           NaN                       NaN         NaN         NaN
10          NaN                        93          90          96
11          NaN                         7           4          10
12          NaN                        <1           0           1
13          NaN                       NaN         NaN         NaN
14          NaN                   8570783         NaN         NaN
15          NaN                       480         NaN         NaN
16          NaN                       NaN         NaN         NaN
17          NaN                       NaN         NaN         NaN
18          NaN                       NaN         NaN         NaN
19          NaN                         4           2           6
20          NaN                        <1           0           1
21          NaN                         1           0           1
22          NaN                        89          86          93
23          NaN                        13           8          18
24          NaN                        86          81          91
25          NaN                        82          76          88
26          NaN                        22          16          28
27          NaN                         4           0           8
28          NaN                       NaN         NaN         NaN
29          NaN                   7946387         NaN         NaN
30          NaN                       440         NaN         NaN
31          NaN                       NaN         NaN         NaN
32          NaN                       NaN         NaN         NaN
33          NaN                       NaN         NaN         NaN
34          NaN                        28          23          34
35          NaN                        20          15          25
36          NaN                        44          38          51
37          NaN                        ..          ..          ..
38          NaN                        ..          ..          ..
39          NaN                        36          30          42
40          NaN                        41          34          47
41          NaN                        15          10          19
42          NaN                         1           0           2
43          NaN                         9           6          13
44          NaN                         5           1           9
45          NaN                         2           0           3
46          NaN                        24          19          30
47          NaN                       NaN         NaN         NaN
48          NaN                   7946387         NaN         NaN
49          NaN                       440         NaN         NaN
50          NaN                       NaN         NaN         NaN

[51 rows x 44 columns]

In [3]:
data.shape

(51, 44)

In [4]:
data.columns

Index(['Table 1b: Cost of living', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3',
       'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8',
       'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12',
       'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16',
       'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20',
       'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24',
       'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28',
       'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32',
       'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35', 'Unnamed: 36',
       'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39', 'Unnamed: 40',
       'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43'],
      dtype='object')

In [5]:
df=data[['Table 1b: Cost of living', 'Unnamed: 1']]
print(df)

                             Table 1b: Cost of living         Unnamed: 1
0                  Great Britain, 16 to 27 March 2022                NaN
1   Source: Opinions and Lifestyle Survey (COVID-1...                NaN
2                       Date published: 25 April 2022                NaN
3   Some cells refer to notes which can be found i...                NaN
4   Freeze panes are turned on. To turn off freeze...                NaN
5                         Return to table of contents                NaN
6                                                 NaN  All persons total
7                                                 NaN                  %
8                                                 NaN                NaN
9   Over the last month, has your cost of living c...                NaN
10                    My cost of living has increased                 87
11              My cost of living has stayed the same                 13
12                    My cost of living has decreased                  1
13                                                NaN                NaN
14                                     Weighted count           52117165
15                                        Sample size               3090
16                                                NaN                NaN
17  Among those who said "My cost of living has in...                NaN
18  Over the last month, for what reasons has your...                NaN
19                 My income or earnings have reduced                  8
20              I have lost my job or stopped working                  1
21                     My hours of work have reduced                   3
22         My gas or electricity bills have increased                 83
23           My rent or mortgage costs have increased                 17
24            The price of my food shop has increased                 88
25                 The price of my fuel has increased                 77
26     The price of my public transport has increased                 15
27                                              Other                  4
28                                                NaN                NaN
29                                     Weighted count           45195052
30                                        Sample size               2730
31                                                NaN                NaN
32  Among those who said "My cost of living has in...                NaN
33  Which of the following are you doing because y...                NaN
34                          I am shopping around more                 37
35  I am spending less on food shopping and essent...                 33
36               I am spending less on non-essentials                 54
37                    I have started using foodbanks                   1
38                          I am using foodbanks more                 <1
39  I am cutting back on non-essential journeys in...                 39
40  I am using less fuel such as gas or electricit...                 45
41                              I am using my savings                 23
42        I am borrowing money from friends or family                  7
43  I am using credit more than usual, for example...                 11
44                 I am working more hours than usual                  5
45                                              Other                  1
46                                      None of these                 12
47                                                NaN                NaN
48                                     Weighted count           45165547
49                                        Sample size               2730
50                                                NaN                NaN

In [20]:
df1=df.iloc[19:28,:]
print(df1)

                          Table 1b: Cost of living Unnamed: 1
19              My income or earnings have reduced          8
20           I have lost my job or stopped working          1
21                  My hours of work have reduced           3
22      My gas or electricity bills have increased         83
23        My rent or mortgage costs have increased         17
24         The price of my food shop has increased         88
25              The price of my fuel has increased         77
26  The price of my public transport has increased         15
27                                           Other          4

In [21]:
df1['Reason for Increase in Cost of Living']=df1['Table 1b: Cost of living']
df1['Percentage']=df['Unnamed: 1']
final_df=df1[['Reason for Increase in Cost of Living','Percentage']].reset_index(inplace=False,drop=True)
print(final_df)

            Reason for Increase in Cost of Living Percentage
0              My income or earnings have reduced          8
1           I have lost my job or stopped working          1
2                  My hours of work have reduced           3
3      My gas or electricity bills have increased         83
4        My rent or mortgage costs have increased         17
5         The price of my food shop has increased         88
6              The price of my fuel has increased         77
7  The price of my public transport has increased         15
8                                           Other          4

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [22]:
final_df.to_csv('Cost_of_living.csv')